### ISSUE TITLE
bsdiff4 no-longer included

### ISSUE THREAD

**Issue by DaJakerBoss** [vm03/payload_dumper#12]
Upon attempting to run the script the user is alerted to the lack of bsdiff4. Installation of the module requires VS Build Tools, and installing the standalone version 14.0 a.k.a Build Tools 2015 does not allow pip to compile it with `pip install bsdiff4`. Would be worth adding to the README and adding instructions for compilation.

![image](https://user-images.githubusercontent.com/33241295/96201857-e32ee600-0f1a-11eb-917b-cf501f7017db.png)

**Comment by vm03** [comment]
I can't reproduce:
pip3 install --user -r requirements.txt       
Collecting protobuf==3.6.0
  Downloading protobuf-3.6.0-py2.py3-none-any.whl (390 kB)
     |████████████████████████████████| 390 kB 906 kB/s 
Collecting six==1.11.0
  Downloading six-1.11.0-py2.py3-none-any.whl (10 kB)
Collecting bsdiff4>=1.1.5
  Downloading bsdiff4-1.2.0.tar.gz (11 kB)
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from protobuf==3.6.0->-r requirements.txt (line 1)) (49.1.3)
Using legacy 'setup.py install' for bsdiff4, since package 'wheel' is not installed.
Installing collected packages: six, protobuf, bsdiff4
    Running setup.py install for bsdiff4 ... done
Successfully installed bsdiff4-1.2.0 protobuf-3.6.0 six-1.11.0

**Comment by carlonzo** [comment]
yes on Ubuntu 20.10 I had to install bsdiff4 separately. 

`pip install bsdiff4`
